easy_admin:
    design:
        menu:
            - { label: 'Jeu Video', entity: 'JeuVideo', icon: 'hand-o-right', params: { sortField: 'nom' , sortDirection: 'ASC'} } 
            - { label: 'Sortie Jeu Video', entity: 'SortieJeuVideo', icon: 'hand-o-right', params: { sortField: 'dateSortie' , sortDirection: 'ASC'} } 
            - { label: 'Note Jeu Video', entity: 'NoteJeuVideo', icon: 'hand-o-right' }
            - { label: 'Tiers', entity: 'Tiers', icon: 'hand-o-right', params: { sortField: 'nom' , sortDirection: 'ASC'} }
            - label: 'Tables secondaires'
              icon: 'plus-circle'
              children:
                  - { entity: 'Support', icon: 'th-list', label: 'Support', params: { sortField: 'nom' , sortDirection: 'ASC'}, default: true }
                  - { entity: 'Nationalite', icon: 'th-list', label: 'Nationalité', params: { sortField: 'nom' , sortDirection: 'ASC'}, default: true }
                  - { entity: 'TypeJeu', icon: 'th-list', label: 'Type jeu', params: { sortField: 'nom' , sortDirection: 'ASC'}, default: true }
                  - { entity: 'ThemeJeu', icon: 'th-list', label: 'Theme jeu', params: { sortField: 'nom' , sortDirection: 'ASC'}, default: true }
                  - { entity: 'ModeJeu', icon: 'th-list', label: 'Mode jeu', params: { sortField: 'nom' , sortDirection: 'ASC'}, default: true }
                  - { entity: 'TypeTiers', icon: 'th-list', label: 'Type tiers', params: { sortField: 'nom' , sortDirection: 'ASC'}, default: true }
                  - { entity: 'AgePegi', icon: 'th-list', label: 'Age PEGI', params: { sortField: 'age' , sortDirection: 'ASC'}, default: true }
                  - { entity: 'ClassificationPegi', icon: 'th-list', label: 'Classification PEGI', params: { sortField: 'nom' , sortDirection: 'ASC'}, default: true }
            - { label: 'Utilisateurs', entity: 'User', icon: 'hand-o-right' }       
