easy_admin:
    entities:
        AgePegi:
            class: JC\SortieJeuVideoBundle\Entity\AgePegi
            list:
                fields:
                    - id
                    - age
                    - { property: 'image', type: 'image', base_path: '%app.path.agepegi_images%' }
            show:
                fields:
                    - id
                    - age
                    - { property: 'image', type: 'image', base_path: '%app.path.agepegi_images%' }
            form:
                fields:
                    - { property: 'id', type_options: { 'disabled': true } }
                    - age
                    - { property: 'imageFile', type: 'vich_image' }
