easy_admin:
    entities:
        ClassificationPegi:
            class: JC\SortieJeuVideoBundle\Entity\ClassificationPegi
            list:
                fields:
                    - id
                    - nom
                    - { property: 'image', type: 'image', base_path: '%app.path.classificationpegi_images%' }
            show:
                fields:
                    - id
                    - nom
                    - { property: 'image', type: 'image', base_path: '%app.path.classificationpegi_images%' }
            form:
                fields:
                    - { property: 'id', type_options: { 'disabled': true } }
                    - nom
                    - { property: 'imageFile', type: 'vich_image' }
