easy_admin:
    entities:
        Tiers:
            class: JC\SortieJeuVideoBundle\Entity\Tiers
            list:
                fields:
                    - id
                    - nom
                    - adresse
                    - site
                    - published
                    - nationalite
                    - typeTiers
                    - { property: 'image', type: 'image', base_path: '%app.path.tiers_images%' }
            show:
                fields:
                    - id
                    - nom
                    - adresse
                    - siteWeb
                    - published
                    - anneeCreation
                    - nationalite
                    - typeTiers
                    - { property: 'image', type: 'image', base_path: '%app.path.tiers_images%' }
            form:
                fields:
                    - { property: 'id', type_options: { 'disabled': true } }
                    - nom
                    - adresse
                    - siteWeb
                    - published
                    - anneeCreation
                    - nationalite
                    - typeTiers
                    - { property: 'imageFile', type: 'vich_image' }