easy_admin:
    entities:
        TypeTiers:
            class: JC\SortieJeuVideoBundle\Entity\TypeTiers
            list:
                fields:
                    - id
                    - nom
            show:
                fields:
                    - id
                    - nom
            form:
                fields:
                    - { property: 'id', type_options: { 'disabled': true } }
                    - nom
