<?php

namespace JC\SortieJeuVideoBundle\Repository;

/**
 * ClassificationPegiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassificationPegiRepository extends \Doctrine\ORM\EntityRepository
{
}
