<?php

namespace JC\SortieJeuVideoBundle\Repository;

/**
 * JeuVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JeuVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
