<?php

namespace JC\SortieJeuVideoBundle\Repository;

/**
 * ModeJeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeJeuRepository extends \Doctrine\ORM\EntityRepository
{
}
