<?php

namespace JC\SortieJeuVideoBundle\Repository;

/**
 * NoteJeuVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteJeuVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
