<?php

namespace JC\SortieJeuVideoBundle\Repository;

/**
 * SortieJeuVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortieJeuVideoRepository extends \Doctrine\ORM\EntityRepository
{

	public function findLastExitGame($limit)
	{

		$qb = $this->createQueryBuilder('a');

		$qb->setMaxResults($limit);

		return $qb->getQuery()->getResult(); 

	}

}
