<?php

namespace JC\SortieJeuVideoBundle\Repository;

/**
 * SortieJeuVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortieJeuVideoRepository extends \Doctrine\ORM\EntityRepository
{

	public function findLastExitGame($limit)
	{

		$qb = $this->createQueryBuilder('a');

		$qb->setMaxResults($limit);
		$qb->orderBy('a.dateSortieRetroXboxOne', 'DESC');

		return $qb->getQuery()->getResult(); 

	}

	public function findCountGame()
	{
		$qb = $this->createQueryBuilder('a');

		$qb->select('COUNT(a)');

		return $qb->getQuery()->getSingleScalarResult(); 

	}

	public function findTripleAGame($limit)
	{

		$qb = $this->createQueryBuilder('a');
		$qb->join('a.jeuVideo','jeu');
		$qb->addSelect('jeu');
		$qb->where('jeu.tripleA = :oui');
		$qb->setParameter('oui', '1');
		$qb->setMaxResults($limit);
		$qb->orderBy('a.dateSortieRetroXboxOne', 'DESC');

		return $qb->getQuery()->getResult();

	}

}
