<?php

namespace JC\SortieJeuVideoBundle\Repository;

/**
 * ThemeJeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeJeuRepository extends \Doctrine\ORM\EntityRepository
{
}
