<?php

namespace JC\SortieJeuVideoBundle\Repository;

/**
 * TypeJeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeJeuRepository extends \Doctrine\ORM\EntityRepository
{
}
