<?php

namespace JC\SortieJeuVideoBundle\Repository;

/**
 * TypeTiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTiersRepository extends \Doctrine\ORM\EntityRepository
{
}
