jc_retroxboxone_homepage:
    path:     /homepage
    defaults: { _controller: JCSortieJeuVideoBundle:RetroXboxOne:index }
jc_retroxboxone_detail:
    path:     /detail/{id}
    defaults: { _controller: JCSortieJeuVideoBundle:RetroXboxOne:detail }    
